"""Uygulama sabitleri."""

DEFAULT_TOP_K = 20
FINAL_TOP_K = 5
MAX_HISTORY_TURNS = 4

MIN_PARAGRAPH_LENGTH = 200
MIN_TEXT_LENGTH = 50

DEFAULT_DPI = 150
MAX_IMAGE_WIDTH = 1200
CONFIDENCE_THRESHOLD = 0.6
